OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: ${OPENAI_API_KEY}

GLMModel:
  model_url: "your_chatglm_model_url"
  timeout: 300

common:
  book: "tests/test.pdf"
  file_format: "markdown"
  source_language: "English"
  target_language: "Chinese"